version: '3.9'

services:
  
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_PASSWORD: changeme
      POSTGRES_USER: course
      POSTGRES_DB: movies
    ports:
      - 5432:5432